version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management 
    hostname: rabbitmq
    container_name: blazorrabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: always

  blazorapp.api:
    image: ${DOCKER_REGISTRY-}blazorappapi
    build:
      context: .
      dockerfile: BlazorApp.Api/Dockerfile
    ports:
     - "50001:50001"

  blazorapp:
    image: ${DOCKER_REGISTRY-}blazorapp
    build:
      context: .
      dockerfile: BlazorApp/Dockerfile
    depends_on:
      - rabbitmq
    ports:
     - "50003:50003"
    command: sh -c "dockerize -wait tcp://rabbitmq:5672 -timeout 30s -wait-retry-interval 3s"
